config/routes.rb
PlaylisterApp::Application.routes.draw do
  resources :genres

  resources :artists

  resources :songs
  resources :users

  resources :mixtapes do
    resources :songs, :controller => 'mixtapes/songs'
    resources :users, :controller => 'mixtapes/users'
  end

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  post '/sessions' => 'sessions#create'

  root 'songs#index'

end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
  has_many :mixtape_songs
  has_many :songs, :through => :mixtape_songs

  has_many :user_mixtapes
  has_many :users, :through => :user_mixtapes

  accepts_nested_attributes_for :songs

  def song_ids_to_add=(song_ids)
    song_ids.each do |song_id|
      self.mixtape_songs.build(:song_id => song_id)
    end
  end



# UserMixtape.create(:user => dj, :mixtape => summer_hits)
# summer_hits.user_mixtapes.create(:user => listener)


end

app/controllers/mixtapes/songs_controller.rb
class Mixtapes::SongsController < ApplicationController

  def new
    @mixtape = Mixtape.find(params[:mixtape_id])
    @song = @mixtape.songs.build
  end

  def create
    @mixtape = Mixtape.find(params[:mixtape_id])
    @song = @mixtape.songs.build(song_params)
    
    @mixtape.save

    redirect_to @mixtape
  end

end

app/controllers/mixtapes/users_controller.rb
class Mixtapes::UsersController < ApplicationController

  def new
    @mixtape = Mixtape.find(params[:mixtape_id])
    @mixtape_user = UserMixtape.new
    @users = User.all - @mixtape.users
  end

  def create
    UserMixtape.create(user_mixtape_params)
    redirect_to mixtape_path(params[:user_mixtape][:mixtape_id])
  end

  private

    def user_mixtape_params
      params.require(:user_mixtape).permit(:user_id, :mixtape_id)
    end

end

#  new_mixtape_song GET    /mixtapes/:mixtape_id/songs/new(.:format)      mixtapes/songs#new

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController

  def new
    @mixtape = Mixtape.new

  end

  def create
    @mixtape = Mixtape.new(mixtape_params)


    params[:mixtape][:songs_attributes].each do |index, song_param|
      new_song = Song.new(song_param)
      @mixtape.mixtape_songs.build(:song => new_song)
    end

    if @mixtape.save
      redirect_to mixtape_path(@mixtape)
    else
      render :new
    end
  end

  def show
    @mixtape = Mixtape.find(params[:id])
  end

  private
    def mixtape_params
      params.require(:mixtape).permit(:name, :song_ids_to_add => [], :song_attributes => {})
    end

end

app/helpers/mixtapes/songs_helper.rb
module Mixtapes::SongsHelper
end

app/helpers/mixtapes/users_helper.rb
module Mixtapes::UsersHelper
end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/views/mixtapes/new.html.erb
<h1>New Mixtape</h1>

<%= form_for(@mixtape) do |f| %>
  <%= f.text_field :name %>

  <%= f.fields_for :songs, Song.new do |song_form| %>
    <%= song_form.text_field :name %>
  <% end %>

  <p>
    <select name="mixtape[song_ids_to_add][]">
      <% Song.all.each do |song| %>
      <option value="<%= song.id %>"><%= song.name %></option>
      <% end %>
    </select>
  </p>



  <%= f.submit %>
<% end %>

app/views/mixtapes/show.html.erb
<h1><%= @mixtape.name %></h1>

<ol>
  <%= render @mixtape.songs %>
</ol>

<h3>Users on this mixtape:</h3>
<ul>
  <% @mixtape.users.each do |user| %>
  <%= user.email %><br>
  <% end %>
</ul>



<p>
  <%= link_to "Add a Song to This Mixtape", new_mixtape_song_path(@mixtape) %>
</p>
<p>
  <%= link_to "Add a User to This Mixtape", new_mixtape_user_path(@mixtape) %>
</p>