config/routes.rb
PlaylisterApp::Application.routes.draw do
  resources :genres

  resources :artists

  resources :songs
  resources :users

  resources :mixtapes do
    resources :songs, :controller => 'mixtapes/songs'
    resources :users, :controller => 'mixtapes/users'
  end

  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  post '/sessions' => 'sessions#create'

  root 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist

  has_many :song_genres
  has_many :genres, :through => :song_genres

  has_many :mixtape_songs    

  validates :name, :presence => true

  def artist_name=(artist_name)
    # Deprecated
    # self.artist = Artist.find_or_create_by_name(artist_name)
    
    # Avi likes these two
    self.artist = Artist.find_or_create_by(:name => artist_name)

    # Avi Doesn't Like This
    # self.artist = Artist.where(:name => artist_name).first_or_create
  end

  def genre_names=(csv_genre_names)
    Genre.find_or_create_by_csv_string(csv_genre_names).each do |genre|
      self.add_genre(genre)
    end
  end

  def add_genre(genre)
    self.song_genres.build(:genre => genre)
  end
end

app/controllers/mixtapes/songs_controller.rb
class Mixtapes::SongsController < ApplicationController

  def new
    @mixtape = Mixtape.find(params[:mixtape_id])
    @song = @mixtape.songs.build
  end

  def create
    @mixtape = Mixtape.find(params[:mixtape_id])
    @song = @mixtape.songs.build(song_params)
    
    @mixtape.save

    redirect_to @mixtape
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
     @song = Song.find(params[:id])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
     @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end


end

app/helpers/mixtapes/songs_helper.rb
module Mixtapes::SongsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label for="song_artist_name">Artist Name</label><br>
    <input type="text" name="song[artist_name]" id="song_artist_name">
  </div>

  <div class="field">
    <label for="song_artist_name">Comma Separated Genres</label><br>
    <input type="text" name="song[genre_names]" id="song_genre_names">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_mixtape_song_form.html.erb
<%= form_for([@mixtape, @song]) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <label for="song_artist_name">Artist Name</label><br>
    <input type="text" name="song[artist_name]" id="song_artist_name">
  </div>

  <div class="field">
    <label for="song_artist_name">Comma Separated Genres</label><br>
    <input type="text" name="song[genre_names]" id="song_genre_names">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<li><%= link_to song.name, song %></li>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<ol>
  <%# @songs.each do |s| %>
    <% # Least Abstract %>
    <%#= render :partial => 'song', :locals => {:song => s} %>
    <% # A little more abstract %>
    <%#= render 'song_li', :song => s %>
    <%#= render s, :as => :s %>
  <%# end %>

  <%#= render :collection => @songs, :partial => 'song_li' %>
  <%= render :collection => @songs, :partial => 'song', :as => :song %>

  <%#= render @songs %>
</ol>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>


  <%= render 'form' %>


<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist Name:</strong>
  <%= link_to @song.artist.name, @song.artist if @song.artist %>
</p>

<p>
  <strong>Genres:</strong>
  <%#= @song.genres.collect(&:name).to_sentence %>
  <%= @song.genres.collect{|g| g.name}.to_sentence %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>